#!/usr/bin/perl
use strict;
use warnings;

use Dpkg::Control::Info;
use Dpkg::Deps;

my $control_info = Dpkg::Control::Info->new();
my $control_fields = $control_info->get_source();
my $build_depends = deps_parse($control_fields->{'Build-Depends'});

my @dependencies = split(/, /, $build_depends);
foreach (@dependencies) {
	if ($_ =~ /\(/) {
		my @versioned_dep = split(/ /, $_);
		$_ = $versioned_dep[0];
		if (substr($versioned_dep[1], 1, 1) eq "=") {
			$_ .= "=" . substr($versioned_dep[2], 0, -1);
		}
	}
}
print join(" ", @dependencies);
