version: 2.1

jobs:

  build:

    docker:
    - image: debian:bookworm-slim

    resource_class: small

    working_directory: /mnt/ramdisk

    steps:

    ## Pre-build setup
    - run:
        name: Configure Apt
        # * Say "yes" automatically
        # * Never want to install "Recommended" packages
        command: |
          echo 'APT::Get::Assume-Yes "true";'     > /etc/apt/apt.conf.d/AssumeYes
          echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/NeverRecommend
    - run:
        name: Update Apt
        command: |
          apt-get update && apt-get upgrade
    - run:
        name: Install build system dependencies
        command: |
          # For CircleCI
          apt-get install git
          # For debian
          apt-get install build-essential debhelper devscripts git-buildpackage

    ## Checkout code
    - checkout

    ## Build
    - run:
        name: Build package
        command: |
          gbp buildpackage

    ## Upload
    - store_artifacts:
        path: debian/build
